set(_CATKIN_CURRENT_PACKAGE "basic_example")
set(basic_example_VERSION "1.0.0")
set(basic_example_MAINTAINER "Julio Jiménez Nájera <juliojn@correo.ugr.es>")
set(basic_example_PACKAGE_FORMAT "2")
set(basic_example_BUILD_DEPENDS "message_generation" "rospy" "std_msgs")
set(basic_example_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(basic_example_BUILDTOOL_DEPENDS "catkin")
set(basic_example_BUILDTOOL_EXPORT_DEPENDS )
set(basic_example_EXEC_DEPENDS "message_runtime" "rospy" "std_msgs")
set(basic_example_RUN_DEPENDS "message_runtime" "rospy" "std_msgs")
set(basic_example_TEST_DEPENDS )
set(basic_example_DOC_DEPENDS )
set(basic_example_URL_WEBSITE "")
set(basic_example_URL_BUGTRACKER "")
set(basic_example_URL_REPOSITORY "")
set(basic_example_DEPRECATED "")